project_id = "buoablhkbfctwmjzeisk"

[functions.ai-recommendations]
verify_jwt = false

[functions.ai-itinerary]
verify_jwt = false

[functions.fetch-crowd-data]
verify_jwt = false

[functions.recognize-landmark]
verify_jwt = false

[functions.generate-missions]
verify_jwt = false
